name: Build App

on:
  repository_dispatch:
    types: [run-ping]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        run: npm ci
      - name: Run Ping
        run: npm run ping